
name: 'sf_dbt_demo1'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'sf_dbt_demo1'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  sf_dbt_demo1: {}

seeds:
  sf_dbt_demo1:
    +database: RAW
    +schema: HEALTH_APP_SRC
