snowflake:
  target: prod
  outputs:
    prod:
      type: snowflake
      # Use JINJA to only include these if the env_var is actually set (GitHub)
      # If running in Snowflake, these will be omitted, which is what Native dbt wants
      {% if env_var('SNOWFLAKE_ACCOUNT', '') != '' %}
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      {% endif %}
      
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "ANALYTICS_DEV"
      schema: "DEV_PIYUSH"
      authenticator: snowflake
      
# snowflake:
#   target: prod
#   outputs:
#     prod:
#       type: snowflake
#       # Fallbacks ('') allow the PROJECT to be created in SF
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') | string }}"
#       user: "{{ env_var('SNOWFLAKE_USER', '') | string }}"
#       password: "{{ env_var('SNOWFLAKE_PASSWORD', '') | string }}"
#       role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') | string }}"
#       warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') | string }}"
#       # HARDCODED DATA DESTINATION (Enterprise Best Practice for Dev/Prod profiles)
#       database: "ANALYTICS_DEV"
#       schema: "DEV_PIYUSH"
#       authenticator: snowflake
  
# snowflake:
#   target: prod
#   outputs:
#     prod:
#       type: snowflake
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#       user: "{{ env_var('SNOWFLAKE_USER') }}"
#       password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
#       role: "{{ env_var('SNOWFLAKE_ROLE') }}"
#       warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
#       database: "{{ env_var('SNOWFLAKE_DB') }}"
#       schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
#       authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR') }}"
