snowflake:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT'), '' }}"
      user: "{{ env_var('SNOWFLAKE_USER'), '' }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD'), '' }}"
      role: "{{ env_var('SNOWFLAKE_ROLE'), 'ACCOUNTADMIN' }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE'), 'COMPUTE_WH' }}"
      database: "{{ env_var('SNOWFLAKE_DB'), 'ANALYTICS_DEV' }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA'), 'DEV_PIYUSH' }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR') }}"


# snowflake:
#   target: prod
#   outputs:
#     prod:
#       type: snowflake
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#       user: "{{ env_var('SNOWFLAKE_USER') }}"
#       password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
#       role: "{{ env_var('SNOWFLAKE_ROLE') }}"
#       warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
#       database: "{{ env_var('SNOWFLAKE_DB') }}"
#       schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
#       authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR') }}"
